### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by rock3r**
This PR improves the `.gitignore` file so you don't get a bunch of untracked files in the repository whenever you clone it, and adds the project icon so it looks better in the projects lists in the IDE and in Toolbox :)

IntelliJ IDEA | Toolbox
--- | ---
Project icon as seen in IntelliJ IDEA | Project icon as seen in Toolbox

⚠️ **This PR requires #460 to be merged, first.** ⚠️ 
The only "actual" changes are the ones to the `.gitignore` and the addition of `.idea/icon.svg` (copied from the plugin icon itself) and `.idea/vcs.xml` (auto-generated by the IDE, but never changes and saves people a popup when cloning).

### CODE REVIEW

**Review by arturbosch — APPROVED** [review]

**Comment by arturbosch** [comment]
@rock3r could you please rebase this PR when you have time?

**Comment by rock3r** [comment]
@arturbosch I have done it but it keeps failing the CI and locally, in ways that seem pretty unrelated to my changes in this PR. Could you take a look?

**Comment by arturbosch** [comment]
> @arturbosch I have done it but it keeps failing the CI and locally, in ways that seem pretty unrelated to my changes in this PR. Could you take a look?

You updated the Gradle wrapper. Current master does only work with Gradle 7.4.2 and Java 11.
I currently work on https://github.com/detekt/detekt-intellij-plugin/pull/463 which will fix all build and test problems with the plugin.

**Review by arturbosch — APPROVED** [review]

**Comment by rock3r** [comment]
Have reverted all build-related changes, let's see if this works now :) Didn't see the PR you were working on, sorry!

**Pull request merged**
