### PR TITLE
Update to Detekt 1.20.0

### PR DESCRIPTION
**Pull request by BorzdeG**
- Update to detekt 1.20.0
- Update to Gradle 7.4.2
- Update Gradle plugins
- Update dependencies
- Update GitHub Actions

### CODE REVIEW

**Comment by BorzdeG** [comment]
@cortinico PR ready

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
This is good to go on my end. @chao2zhang what's your take?

**Comment by chao2zhang** [comment]
👍  I will proceed with publishing

**Comment by TWiStErRob** [comment]
@chao2zhang I can't see 1.20.0 on Jetbrains: https://plugins.jetbrains.com/plugin/10761-detekt

**Comment by BorzdeG** [comment]
@TWiStErRob actions fail: https://github.com/detekt/detekt-intellij-plugin/actions/runs/2203070637 ...

**Comment by chao2zhang** [comment]
I will need to look into https://github.com/detekt/detekt-intellij-plugin/issues/158 today. Otherwise I will fallback to use my old laptop to publish.

**Pull request merged**
